[env:gateway]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
monitor_filters = time, colorize
lib_deps =
  jgromes/RadioLib
  olikraus/U8g2
build_flags =
  -D CORE_DEBUG_LEVEL=0
